// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CreateContainerEntryPointScript.proto

package rpcServer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateScriptRequest struct {
	Pwd                  string   `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Cmd                  []string `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScriptRequest) Reset()         { *m = CreateScriptRequest{} }
func (m *CreateScriptRequest) String() string { return proto.CompactTextString(m) }
func (*CreateScriptRequest) ProtoMessage()    {}
func (*CreateScriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d3af79e1fae8dd, []int{0}
}

func (m *CreateScriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScriptRequest.Unmarshal(m, b)
}
func (m *CreateScriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScriptRequest.Marshal(b, m, deterministic)
}
func (m *CreateScriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScriptRequest.Merge(m, src)
}
func (m *CreateScriptRequest) XXX_Size() int {
	return xxx_messageInfo_CreateScriptRequest.Size(m)
}
func (m *CreateScriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScriptRequest proto.InternalMessageInfo

func (m *CreateScriptRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *CreateScriptRequest) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type CreateScriptResponse struct {
	ErrMessage           string   `protobuf:"bytes,1,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScriptResponse) Reset()         { *m = CreateScriptResponse{} }
func (m *CreateScriptResponse) String() string { return proto.CompactTextString(m) }
func (*CreateScriptResponse) ProtoMessage()    {}
func (*CreateScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d3af79e1fae8dd, []int{1}
}

func (m *CreateScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScriptResponse.Unmarshal(m, b)
}
func (m *CreateScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScriptResponse.Marshal(b, m, deterministic)
}
func (m *CreateScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScriptResponse.Merge(m, src)
}
func (m *CreateScriptResponse) XXX_Size() int {
	return xxx_messageInfo_CreateScriptResponse.Size(m)
}
func (m *CreateScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScriptResponse proto.InternalMessageInfo

func (m *CreateScriptResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateScriptRequest)(nil), "rpcServer.CreateScriptRequest")
	proto.RegisterType((*CreateScriptResponse)(nil), "rpcServer.CreateScriptResponse")
}

func init() {
	proto.RegisterFile("CreateContainerEntryPointScript.proto", fileDescriptor_84d3af79e1fae8dd)
}

var fileDescriptor_84d3af79e1fae8dd = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x75, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x75, 0xce, 0xcf, 0x2b, 0x49, 0xcc, 0xcc, 0x4b, 0x2d, 0x72, 0xcd, 0x2b, 0x29, 0xaa,
	0x0c, 0xc8, 0xcf, 0xcc, 0x2b, 0x09, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x2c, 0x2a, 0x48, 0x0e, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x52, 0xb2, 0xe4, 0x12,
	0x86, 0xe8, 0x81, 0x28, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e,
	0x28, 0x4f, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xc9, 0xb9, 0x29,
	0x12, 0x4c, 0x0a, 0xcc, 0x20, 0x91, 0xe4, 0xdc, 0x14, 0x25, 0x33, 0x2e, 0x11, 0x54, 0xad, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x72, 0x5c, 0x5c, 0xa9, 0x45, 0x45, 0xbe, 0xa9, 0xc5, 0xc5,
	0x89, 0xe9, 0xa9, 0x50, 0x23, 0x90, 0x44, 0x8c, 0x4a, 0xb8, 0xe4, 0x09, 0x38, 0x53, 0x28, 0x90,
	0x8b, 0x07, 0xd9, 0x68, 0x21, 0x39, 0x3d, 0xb8, 0x8b, 0xf5, 0xb0, 0x38, 0x57, 0x4a, 0x1e, 0xa7,
	0x3c, 0xc4, 0x4d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xaf, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x17, 0x7c, 0x9c, 0x81, 0x23, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateContainerEntryPointScriptClient is the client API for CreateContainerEntryPointScript service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateContainerEntryPointScriptClient interface {
	CreateScript(ctx context.Context, in *CreateScriptRequest, opts ...grpc.CallOption) (*CreateScriptResponse, error)
}

type createContainerEntryPointScriptClient struct {
	cc *grpc.ClientConn
}

func NewCreateContainerEntryPointScriptClient(cc *grpc.ClientConn) CreateContainerEntryPointScriptClient {
	return &createContainerEntryPointScriptClient{cc}
}

func (c *createContainerEntryPointScriptClient) CreateScript(ctx context.Context, in *CreateScriptRequest, opts ...grpc.CallOption) (*CreateScriptResponse, error) {
	out := new(CreateScriptResponse)
	err := c.cc.Invoke(ctx, "/rpcServer.CreateContainerEntryPointScript/CreateScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateContainerEntryPointScriptServer is the server API for CreateContainerEntryPointScript service.
type CreateContainerEntryPointScriptServer interface {
	CreateScript(context.Context, *CreateScriptRequest) (*CreateScriptResponse, error)
}

// UnimplementedCreateContainerEntryPointScriptServer can be embedded to have forward compatible implementations.
type UnimplementedCreateContainerEntryPointScriptServer struct {
}

func (*UnimplementedCreateContainerEntryPointScriptServer) CreateScript(ctx context.Context, req *CreateScriptRequest) (*CreateScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScript not implemented")
}

func RegisterCreateContainerEntryPointScriptServer(s *grpc.Server, srv CreateContainerEntryPointScriptServer) {
	s.RegisterService(&_CreateContainerEntryPointScript_serviceDesc, srv)
}

func _CreateContainerEntryPointScript_CreateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateContainerEntryPointScriptServer).CreateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcServer.CreateContainerEntryPointScript/CreateScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateContainerEntryPointScriptServer).CreateScript(ctx, req.(*CreateScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CreateContainerEntryPointScript_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcServer.CreateContainerEntryPointScript",
	HandlerType: (*CreateContainerEntryPointScriptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScript",
			Handler:    _CreateContainerEntryPointScript_CreateScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CreateContainerEntryPointScript.proto",
}
